CREATE TABLE estados_pedidos (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
id_estado INT NOT NULL,
id_pedidos INT NOT NULL,
hora DATETIME
);
ALTER TABLE estados_pedidos
ADD CONSTRAINT FK_ESTADOS_PEDIDOS_ESTADO
FOREIGN KEY (id_estado) REFERENCES estados(id);

ALTER TABLE estados_pedidos
ADD CONSTRAINT FK_ESTADOS_PEDIDOS_PEDIDOS
FOREIGN KEY (id_pedidos) REFERENCES pedidos(id);