CREATE TABLE pedidos (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
id_usuarios INT NOT NULL,
id_forma_pago INT NOT NULL,
id_estado INT NOT NULL,
hora TIME,
precio_total DECIMAL (9,2) NOT NULL,
pagado BIT(1)
);
SELECT * FROM pedidos;

ALTER TABLE pedidos
ADD CONSTRAINT FK_PEDIDOS_USUARIOS
FOREIGN KEY (id_usuarios) REFERENCES usuarios(id);

ALTER TABLE pedidos
ADD CONSTRAINT FK_PEDIDOS_FORMA_PAGO
FOREIGN KEY (id_forma_pago) REFERENCES formas_de_pago(id);

ALTER TABLE pedidos
ADD CONSTRAINT FK_PEDIDOS_ESTADO
FOREIGN KEY (id_estado) REFERENCES estados(id);


